[window]
decorations = "none"
padding = { x = 10, y = 4 }
opacity = 0.9

[font]
size = 12
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
